[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: Skrajnie krytyczne testy weryfikujące główne ścieżki
    selenium: Testy Selenium
    register: Testy rejestracji
    regression: Pełne testy regresyjne
    elements: Testy sekcji Elements na stronie DemoQA
    xd: xd
    create_employee: Testy tworzenia pracownika
    wip: Work in progress
    auth: Testy autoryzacji
    onet: onet

